netbox/netbox-4.4.4/netbox/extras/api/urls.py
from django.urls import include, path

from core.api.views import ObjectTypeViewSet
from netbox.api.routers import NetBoxRouter
from . import views


router = NetBoxRouter()
router.APIRootView = views.ExtrasRootView

router.register('event-rules', views.EventRuleViewSet)
router.register('webhooks', views.WebhookViewSet)
router.register('custom-fields', views.CustomFieldViewSet)
router.register('custom-field-choice-sets', views.CustomFieldChoiceSetViewSet)
router.register('custom-links', views.CustomLinkViewSet)
router.register('export-templates', views.ExportTemplateViewSet)
router.register('saved-filters', views.SavedFilterViewSet)
router.register('table-configs', views.TableConfigViewSet)
router.register('bookmarks', views.BookmarkViewSet)
router.register('notifications', views.NotificationViewSet)
router.register('notification-groups', views.NotificationGroupViewSet)
router.register('subscriptions', views.SubscriptionViewSet)
router.register('tags', views.TagViewSet)
router.register('tagged-objects', views.TaggedItemViewSet)
router.register('image-attachments', views.ImageAttachmentViewSet)
router.register('journal-entries', views.JournalEntryViewSet)
router.register('config-contexts', views.ConfigContextViewSet)
router.register('config-context-profiles', views.ConfigContextProfileViewSet)
router.register('config-templates', views.ConfigTemplateViewSet)
router.register('scripts', views.ScriptViewSet, basename='script')

# TODO: Remove in NetBox v4.5
router.register('object-types', ObjectTypeViewSet)

app_name = 'extras-api'
urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('', include(router.urls)),
]

netbox/netbox-4.4.4/netbox/extras/urls.py
from django.urls import include, path

from extras import views
from utilities.urls import get_model_urls


app_name = 'extras'
urlpatterns = [

    path('custom-fields/', include(get_model_urls('extras', 'customfield', detail=False))),
    path('custom-fields/<int:pk>/', include(get_model_urls('extras', 'customfield'))),

    path('custom-field-choices/', include(get_model_urls('extras', 'customfieldchoiceset', detail=False))),
    path('custom-field-choices/<int:pk>/', include(get_model_urls('extras', 'customfieldchoiceset'))),

    path('custom-links/', include(get_model_urls('extras', 'customlink', detail=False))),
    path('custom-links/<int:pk>/', include(get_model_urls('extras', 'customlink'))),

    path('export-templates/', include(get_model_urls('extras', 'exporttemplate', detail=False))),
    path('export-templates/<int:pk>/', include(get_model_urls('extras', 'exporttemplate'))),

    path('table-configs/', include(get_model_urls('extras', 'tableconfig', detail=False))),
    path('table-configs/<int:pk>/', include(get_model_urls('extras', 'tableconfig'))),

    path('saved-filters/', include(get_model_urls('extras', 'savedfilter', detail=False))),
    path('saved-filters/<int:pk>/', include(get_model_urls('extras', 'savedfilter'))),

    path('bookmarks/', include(get_model_urls('extras', 'bookmark', detail=False))),
    path('bookmarks/<int:pk>/', include(get_model_urls('extras', 'bookmark'))),

    path('notification-groups/', include(get_model_urls('extras', 'notificationgroup', detail=False))),
    path('notification-groups/<int:pk>/', include(get_model_urls('extras', 'notificationgroup'))),

    path('notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('notifications/', include(get_model_urls('extras', 'notification', detail=False))),
    path('notifications/<int:pk>/', include(get_model_urls('extras', 'notification'))),

    path('subscriptions/', include(get_model_urls('extras', 'subscription', detail=False))),
    path('subscriptions/<int:pk>/', include(get_model_urls('extras', 'subscription'))),

    path('webhooks/', include(get_model_urls('extras', 'webhook', detail=False))),
    path('webhooks/<int:pk>/', include(get_model_urls('extras', 'webhook'))),

    path('event-rules/', include(get_model_urls('extras', 'eventrule', detail=False))),
    path('event-rules/<int:pk>/', include(get_model_urls('extras', 'eventrule'))),

    path('tags/', include(get_model_urls('extras', 'tag', detail=False))),
    path('tags/<int:pk>/', include(get_model_urls('extras', 'tag'))),

    path('config-context-profiles/', include(get_model_urls('extras', 'configcontextprofile', detail=False))),
    path('config-context-profiles/<int:pk>/', include(get_model_urls('extras', 'configcontextprofile'))),

    path('config-contexts/', include(get_model_urls('extras', 'configcontext', detail=False))),
    path('config-contexts/<int:pk>/', include(get_model_urls('extras', 'configcontext'))),

    path('config-templates/', include(get_model_urls('extras', 'configtemplate', detail=False))),
    path('config-templates/<int:pk>/', include(get_model_urls('extras', 'configtemplate'))),

    path('image-attachments/', include(get_model_urls('extras', 'imageattachment', detail=False))),
    path('image-attachments/<int:pk>/', include(get_model_urls('extras', 'imageattachment'))),

    path('journal-entries/', include(get_model_urls('extras', 'journalentry', detail=False))),
    path('journal-entries/<int:pk>/', include(get_model_urls('extras', 'journalentry'))),

    # User dashboard
    path('dashboard/reset/', views.DashboardResetView.as_view(), name='dashboard_reset'),
    path('dashboard/widgets/add/', views.DashboardWidgetAddView.as_view(), name='dashboardwidget_add'),
    path(
        'dashboard/widgets/<uuid:id>/configure/',
        views.DashboardWidgetConfigView.as_view(),
        name='dashboardwidget_config'
    ),
    path(
        'dashboard/widgets/<uuid:id>/delete/',
        views.DashboardWidgetDeleteView.as_view(),
        name='dashboardwidget_delete'
    ),

    # Scripts
    path('scripts/', views.ScriptListView.as_view(), name='script_list'),
    path('scripts/add/', views.ScriptModuleCreateView.as_view(), name='scriptmodule_add'),
    path('scripts/results/<int:job_pk>/', views.ScriptResultView.as_view(), name='script_result'),
    path('scripts/<int:pk>/', views.ScriptView.as_view(), name='script'),
    path('scripts/<str:module>.<str:name>/', views.ScriptView.as_view(), name='script'),
    path('scripts/<int:pk>/source/', views.ScriptSourceView.as_view(), name='script_source'),
    path('scripts/<str:module>.<str:name>/source/', views.ScriptSourceView.as_view(), name='script_source'),
    path('scripts/<int:pk>/jobs/', views.ScriptJobsView.as_view(), name='script_jobs'),
    path('scripts/<str:module>.<str:name>/jobs/', views.ScriptJobsView.as_view(), name='script_jobs'),
    path('script-modules/<int:pk>/', include(get_model_urls('extras', 'scriptmodule'))),

    # Markdown
    path('render/markdown/', views.RenderMarkdownView.as_view(), name="render_markdown"),
]

netbox/netbox-4.4.4/netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.decorators.cache import cache_page
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from account.views import LoginView, LogoutView
from netbox.api.views import APIRootView, StatusView
from netbox.graphql.schema import schema
from netbox.graphql.views import NetBoxGraphQLView
from netbox.plugins.urls import plugin_patterns, plugin_api_patterns
from netbox.views import HomeView, MediaView, StaticMediaFailureView, SearchView, htmx

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('core/', include('core.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('users/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),
    path('vpn/', include('vpn.urls')),
    path('wireless/', include('wireless.urls')),

    # Current user views
    path('user/', include('account.urls')),

    # HTMX views
    path('htmx/object-selector/', htmx.ObjectSelectorView.as_view(), name='htmx_object_selector'),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/core/', include('core.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/vpn/', include('vpn.api.urls')),
    path('api/wireless/', include('wireless.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),

    path(
        "api/schema/",
        cache_page(timeout=86400, key_prefix=f"api_schema_{settings.RELEASE.version}")(
            SpectacularAPIView.as_view()
        ),
        name="schema",
    ),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),

    # GraphQL
    path('graphql/', NetBoxGraphQLView.as_view(schema=schema), name='graphql'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', MediaView.as_view(), name='media'),
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),
]

# django-debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    _patterns.append(path('__debug__/', include(debug_toolbar.urls)))

# Prometheus metrics
if settings.METRICS_ENABLED:
    _patterns.append(path('', include('django_prometheus.urls')))

# Prepend BASE_PATH
urlpatterns = [
    path(settings.BASE_PATH, include(_patterns))
]

handler404 = 'netbox.views.errors.handler_404'
handler500 = 'netbox.views.errors.handler_500'

netbox/netbox-4.4.4/netbox/vpn/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views  # noqa F401

app_name = 'vpn'
urlpatterns = [

    path('tunnel-groups/', include(get_model_urls('vpn', 'tunnelgroup', detail=False))),
    path('tunnel-groups/<int:pk>/', include(get_model_urls('vpn', 'tunnelgroup'))),

    path('tunnels/', include(get_model_urls('vpn', 'tunnel', detail=False))),
    path('tunnels/<int:pk>/', include(get_model_urls('vpn', 'tunnel'))),

    path('tunnel-terminations/', include(get_model_urls('vpn', 'tunneltermination', detail=False))),
    path('tunnel-terminations/<int:pk>/', include(get_model_urls('vpn', 'tunneltermination'))),

    path('ike-proposals/', include(get_model_urls('vpn', 'ikeproposal', detail=False))),
    path('ike-proposals/<int:pk>/', include(get_model_urls('vpn', 'ikeproposal'))),

    path('ike-policies/', include(get_model_urls('vpn', 'ikepolicy', detail=False))),
    path('ike-policies/<int:pk>/', include(get_model_urls('vpn', 'ikepolicy'))),

    path('ipsec-proposals/', include(get_model_urls('vpn', 'ipsecproposal', detail=False))),
    path('ipsec-proposals/<int:pk>/', include(get_model_urls('vpn', 'ipsecproposal'))),

    path('ipsec-policies/', include(get_model_urls('vpn', 'ipsecpolicy', detail=False))),
    path('ipsec-policies/<int:pk>/', include(get_model_urls('vpn', 'ipsecpolicy'))),

    path('ipsec-profiles/', include(get_model_urls('vpn', 'ipsecprofile', detail=False))),
    path('ipsec-profiles/<int:pk>/', include(get_model_urls('vpn', 'ipsecprofile'))),

    path('l2vpns/', include(get_model_urls('vpn', 'l2vpn', detail=False))),
    path('l2vpns/<int:pk>/', include(get_model_urls('vpn', 'l2vpn'))),

    path('l2vpn-terminations/', include(get_model_urls('vpn', 'l2vpntermination', detail=False))),
    path('l2vpn-terminations/<int:pk>/', include(get_model_urls('vpn', 'l2vpntermination'))),

]

netbox/netbox-4.4.4/netbox/extras/models/search.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from netbox.search.utils import get_indexer
from utilities.fields import RestrictedGenericForeignKey
from ..fields import CachedValueField

__all__ = (
    'CachedValue',
)


class CachedValue(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    timestamp = models.DateTimeField(
        verbose_name=_('timestamp'),
        auto_now_add=True,
        editable=False
    )
    object_type = models.ForeignKey(
        to='contenttypes.ContentType',
        on_delete=models.CASCADE,
        related_name='+'
    )
    object_id = models.PositiveBigIntegerField()
    object = RestrictedGenericForeignKey(
        ct_field='object_type',
        fk_field='object_id'
    )
    field = models.CharField(
        verbose_name=_('field'),
        max_length=200
    )
    type = models.CharField(
        verbose_name=_('type'),
        max_length=30
    )
    value = CachedValueField(
        verbose_name=_('value'),
    )
    weight = models.PositiveSmallIntegerField(
        verbose_name=_('weight'),
        default=1000
    )

    _netbox_private = True

    class Meta:
        ordering = ('weight', 'object_type', 'value', 'object_id')
        verbose_name = _('cached value')
        verbose_name_plural = _('cached values')
        indexes = (
            models.Index(fields=('object_type', 'object_id'), name='extras_cachedvalue_object'),
        )

    def __str__(self):
        return f'{self.object_type} {self.object_id}: {self.field}={self.value}'

    @property
    def display_attrs(self):
        """
        Render any display attributes associated with this search result.
        """
        indexer = get_indexer(self.object_type)
        attrs = {}
        for attr in indexer.display_attrs:
            name = self.object._meta.get_field(attr).verbose_name
            if value := getattr(self.object, attr):
                if display_func := getattr(self.object, f'get_{attr}_display', None):
                    attrs[name] = display_func()
                else:
                    attrs[name] = value
        return attrs

netbox/netbox-4.4.4/netbox/extras/dashboard/forms.py
from django import forms
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

from extras.choices import DashboardWidgetColorChoices
from netbox.registry import registry
from utilities.forms import add_blank_choice

__all__ = (
    'DashboardWidgetAddForm',
    'DashboardWidgetForm',
)


def get_widget_choices():
    return registry['widgets'].items()


class DashboardWidgetForm(forms.Form):
    title = forms.CharField(
        required=False
    )
    color = forms.ChoiceField(
        choices=add_blank_choice(DashboardWidgetColorChoices),
        required=False,
    )


class DashboardWidgetAddForm(DashboardWidgetForm):
    widget_class = forms.ChoiceField(
        choices=get_widget_choices,
        widget=forms.Select(
            attrs={
                'hx-get': reverse_lazy('extras:dashboardwidget_add'),
                'hx-target': '#widget_add_form',
            }
        ),
        label=_('Widget type')
    )
    field_order = ('widget_class', 'title', 'color')

netbox/netbox-4.4.4/netbox/extras/forms/misc.py
from django import forms
from django.utils.translation import gettext_lazy as _

__all__ = (
    'RenderMarkdownForm',
)


class RenderMarkdownForm(forms.Form):
    """
    Provides basic validation for markup to be rendered.
    """
    text = forms.CharField(
        label=_('Text'),
        required=False
    )

netbox/netbox-4.4.4/netbox/extras/forms/reports.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.choices import JobIntervalChoices
from utilities.forms.widgets import DateTimePicker, NumberWithOptions
from utilities.datetime import local_now

__all__ = (
    'ReportForm',
)


class ReportForm(forms.Form):
    schedule_at = forms.DateTimeField(
        required=False,
        widget=DateTimePicker(),
        label=_("Schedule at"),
        help_text=_("Schedule execution of report to a set time"),
    )
    interval = forms.IntegerField(
        required=False,
        min_value=1,
        label=_("Recurs every"),
        widget=NumberWithOptions(
            options=JobIntervalChoices
        ),
        help_text=_("Interval at which this report is re-run (in minutes)")
    )

    def __init__(self, *args, scheduling_enabled=True, **kwargs):
        super().__init__(*args, **kwargs)

        # Annotate the current system time for reference
        now = local_now().strftime('%Y-%m-%d %H:%M:%S %Z')
        self.fields['schedule_at'].help_text += _(' (current time: <strong>{now}</strong>)').format(now=now)

        # Remove scheduling fields if scheduling is disabled
        if not scheduling_enabled:
            self.fields.pop('schedule_at')
            self.fields.pop('interval')

    def clean(self):
        scheduled_time = self.cleaned_data.get('schedule_at')
        if scheduled_time and scheduled_time < local_now():
            raise forms.ValidationError(_('Scheduled time must be in the future.'))

        # When interval is used without schedule at, schedule for the current time
        if self.cleaned_data.get('interval') and not scheduled_time:
            self.cleaned_data['schedule_at'] = local_now()

        return self.cleaned_data

netbox/netbox-4.4.4/netbox/templates/extras/customfield.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load i18n %}

{% block content %}
<div class="row mb-3">
	<div class="col col-12 col-md-6">
    <div class="card">
      <h2 class="card-header">{% trans "Custom Field" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">{% trans "Name" %}</th>
          <td>{{ object.name }}</td>
        </tr>
        <tr>
          <th scope="row">Type</th>
          <td>
            {{ object.get_type_display }}
            {% if object.related_object_type %}
              ({{ object.related_object_type.model|bettertitle }})
            {% endif %}
          </td>
        </tr>
        <tr>
          <th scope="row">{% trans "Label" %}</th>
          <td>{{ object.label|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Group Name" %}</th>
          <td>{{ object.group_name|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Description" %}</th>
          <td>{{ object.description|markdown|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Required" %}</th>
          <td>{% checkmark object.required %}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Must be Unique" %}</th>
          <td>{% checkmark object.unique %}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Cloneable" %}</th>
          <td>{% checkmark object.is_cloneable %}</td>
        </tr>
        {% if object.choice_set %}
          <tr>
            <th scope="row">{% trans "Choice Set" %}</th>
            <td>{{ object.choice_set|linkify }} ({{ object.choice_set.choices|length }} choices)</td>
          </tr>
        {% endif %}
        <tr>
          <th scope="row">{% trans "Default Value" %}</th>
          <td>{{ object.default }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Related object filter" %}</th>
          {% if object.related_object_filter %}
            <td><pre>{{ object.related_object_filter|json }}</pre></td>
          {% else %}
            <td>{{ ''|placeholder }}</td>
          {% endif %}
        </tr>
      </table>
    </div>
    <div class="card">
      <h2 class="card-header">{% trans "Behavior" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">{% trans "Search Weight" %}</th>
          <td>
            {% if object.search_weight %}
              {{ object.search_weight }}
            {% else %}
              <span class="text-muted">{% trans "Disabled" %}</span>
            {% endif %}
          </td>
        </tr>
        <tr>
          <th scope="row">{% trans "Filter Logic" %}</th>
          <td>{{ object.get_filter_logic_display }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Display Weight" %}</th>
          <td>{{ object.weight }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "UI Visible" %}</th>
          <td>{{ object.get_ui_visible_display }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "UI Editable" %}</th>
          <td>{{ object.get_ui_editable_display }}</td>
        </tr>
      </table>
    </div>
    {% include 'inc/panels/comments.html' %}
    {% plugin_left_page object %}
	</div>
	<div class="col col-12 col-md-6">
    <div class="card">
      <h2 class="card-header">{% trans "Object Types" %}</h2>
      <table class="table table-hover attr-table">
        {% for ct in object.object_types.all %}
          <tr>
            <td>{{ ct }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    <div class="card">
      <h2 class="card-header">{% trans "Validation Rules" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">{% trans "Minimum Value" %}</th>
          <td>{{ object.validation_minimum|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Maximum Value" %}</th>
          <td>{{ object.validation_maximum|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Regular Expression" %}</th>
          <td>
            {% if object.validation_regex %}
              <code>{{ object.validation_regex }}</code>
            {% else %}
              {{ ''|placeholder }}
            {% endif %}
          </td>
        </tr>
      </table>
    </div>
    <div class="card">
      <h2 class="card-header">Related Objects</h2>
      <ul class="list-group list-group-flush" role="presentation">
        {% for qs in related_models %}
          <a class="list-group-item list-group-item-action d-flex justify-content-between">
            {{ qs.model|meta:"verbose_name_plural"|bettertitle }}
            {% with count=qs.count %}
              {% if count %}
                <span class="badge text-bg-primary rounded-pill">{{ count }}</span>
              {% else %}
                <span class="badge text-bg-light rounded-pill">&mdash;</span>
              {% endif %}
            {% endwith %}
          </a>
        {% endfor %}
      </ul>
    </div>

    {% plugin_right_page object %}
  </div>
</div>
<div class="row">
  <div class="col col-md-12">
    {% plugin_full_width_page object %}
  </div>
</div>
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/extras/script_list.html
{% extends 'generic/_base.html' %}
{% load buttons %}
{% load helpers %}
{% load perms %}
{% load i18n %}

{% block title %}{% trans "Scripts" %}{% endblock %}

{% block tabs %}
  <ul class="nav nav-tabs">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" role="tab">{% trans "Scripts" %}</a>
    </li>
  </ul>
{% endblock tabs %}

{% block controls %}
  {% add_button model %}
{% endblock controls %}

{% block content %}
  {% include 'extras/inc/script_list_content.html' with embedded=False %}
{% endblock content %}

netbox/netbox-4.4.4/netbox/templates/extras/script_result.html
{% extends 'generic/_base.html' %}
{% load helpers %}
{% load buttons %}
{% load perms %}
{% load i18n %}

{% block title %}{{ script }}{% endblock %}

{% block subtitle %}
  {{ script.Meta.description|markdown }}
{% endblock %}

{% block page-header %}
  <div class="container-fluid mt-2">
    <nav class="breadcrumb-container" aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'extras:script_list' %}">{% trans "Scripts" %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'extras:script_list' %}#module.{{ script.module }}">{{ script.module|bettertitle }}</a></li>
        <li class="breadcrumb-item"><a href="{{ script.get_absolute_url }}">{{ script }}</a></li>
        <li class="breadcrumb-item">{{ job.created|isodatetime }}</li>
      </ol>
    </nav>
  </div>
{% endblock page-header %}

{% block controls %}
  {% if request.user|can_delete:job %}
    {% delete_button job %}
  {% endif %}
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a href="#results" role="tab" data-bs-toggle="tab" class="nav-link active">{% trans "Results" %}</a>
    </li>
  </ul>
{% endblock %}

{% block content %}
    {# Object list tab #}
    <div class="tab-pane show active" id="results" role="tabpanel" aria-labelledby="results-tab">

      {# Object table controls #}
      <div class="d-flex align-items-center mb-3">
        <div>{% trans "Log threshold" %}</div>

        <div class="px-2 d-print-none">
          <div class="dropdown">
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ log_levels|get_key:log_threshold }}
            </button>
            <div class="dropdown-menu">
              {% for level, name in log_levels.items %}
                <a class="dropdown-item d-flex justify-content-between" href="{% url 'extras:script_result' job_pk=job.pk %}?log_threshold={{ level }}">
                  {{ name }}{% if forloop.counter == 1 %} ({% trans "All" %}){% elif forloop.counter == 2 %} ({% trans "Default" %}){% endif %}
                  {% if level == log_threshold %}<span class="badge bg-green ms-auto"></span>{% endif %}
                </a>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="ms-auto d-print-none">
          {% if request.user.is_authenticated and job.completed %}
            <div class="table-configure input-group">
              <button type="button" data-bs-toggle="modal" title="{% trans "Configure Table" %}" data-bs-target="#ObjectTable_config"
                class="btn">
                <i class="mdi mdi-cog"></i> {% trans "Configure Table" %}
              </button>
            </div>
          {% endif %}
        </div>
      </div>

      <form method="post" class="form form-horizontal">
        {% csrf_token %}
        {# "Select all" form #}
        {% if table.paginator.num_pages > 1 %}
          <div id="select-all-box" class="d-none card d-print-none">
            <div class="form col-md-12">
              <div class="card-body">
                <div class="form-check">
                  <input type="checkbox" id="select-all" name="_all" class="form-check-input" />
                  <label for="select-all" class="form-check-label">
                    {% blocktrans trimmed with count=table.rows|length object_type_plural=table.data.verbose_name_plural %}
                      Select <strong>all {{ count }} {{ object_type_plural }}</strong> matching query
                    {% endblocktrans %}
                  </label>
                </div>
              </div>
            </div>
          </div>
        {% endif %}

        <div class="form form-horizontal">
          {% csrf_token %}
          <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

          {# Objects table #}
            <div class="col col-md-12"{% if not job.completed %} hx-get="{% url 'extras:script_result' job_pk=job.pk %}" hx-trigger="load delay:0.5s, every 5s"{% endif %}>
              {% include 'extras/htmx/script_result.html' %}
            </div>
          {# /Objects table #}

        </div>
      </form>
    </div>
    {# /Object list tab #}

{% endblock content %}

{% block modals %}
  {% if job.completed %}
  {% table_config_form table table_name="ObjectTable" %}
  {% endif %}
{% endblock modals %}