netbox/netbox-4.4.4/netbox/core/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views

app_name = 'core'
urlpatterns = (

    path('data-sources/', include(get_model_urls('core', 'datasource', detail=False))),
    path('data-sources/<int:pk>/', include(get_model_urls('core', 'datasource'))),

    path('data-files/', include(get_model_urls('core', 'datafile', detail=False))),
    path('data-files/<int:pk>/', include(get_model_urls('core', 'datafile'))),

    path('jobs/', include(get_model_urls('core', 'job', detail=False))),
    path('jobs/<int:pk>/', include(get_model_urls('core', 'job'))),

    path('changelog/', include(get_model_urls('core', 'objectchange', detail=False))),
    path('changelog/<int:pk>/', include(get_model_urls('core', 'objectchange'))),

    # Background Tasks
    path('background-queues/', views.BackgroundQueueListView.as_view(), name='background_queue_list'),
    path(
        'background-queues/<int:queue_index>/<str:status>/',
        views.BackgroundTaskListView.as_view(),
        name='background_task_list'
    ),
    path('background-tasks/<str:job_id>/', views.BackgroundTaskView.as_view(), name='background_task'),
    path(
        'background-tasks/<str:job_id>/delete/',
        views.BackgroundTaskDeleteView.as_view(),
        name='background_task_delete'
    ),
    path(
        'background-tasks/<str:job_id>/requeue/',
        views.BackgroundTaskRequeueView.as_view(),
        name='background_task_requeue'
    ),
    path(
        'background-tasks/<str:job_id>/enqueue/',
        views.BackgroundTaskEnqueueView.as_view(),
        name='background_task_enqueue'
    ),
    path('background-tasks/<str:job_id>/stop/', views.BackgroundTaskStopView.as_view(), name='background_task_stop'),
    path('background-workers/<int:queue_index>/', views.WorkerListView.as_view(), name='worker_list'),
    path('background-workers/<str:key>/', views.WorkerView.as_view(), name='worker'),

    path('config-revisions/', include(get_model_urls('core', 'configrevision', detail=False))),
    path('config-revisions/<int:pk>/', include(get_model_urls('core', 'configrevision'))),

    path('system/', views.SystemView.as_view(), name='system'),

    path('plugins/', views.PluginListView.as_view(), name='plugin_list'),
    path('plugins/<str:name>/', views.PluginView.as_view(), name='plugin'),
)

netbox/netbox-4.4.4/netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.decorators.cache import cache_page
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from account.views import LoginView, LogoutView
from netbox.api.views import APIRootView, StatusView
from netbox.graphql.schema import schema
from netbox.graphql.views import NetBoxGraphQLView
from netbox.plugins.urls import plugin_patterns, plugin_api_patterns
from netbox.views import HomeView, MediaView, StaticMediaFailureView, SearchView, htmx

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('core/', include('core.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('users/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),
    path('vpn/', include('vpn.urls')),
    path('wireless/', include('wireless.urls')),

    # Current user views
    path('user/', include('account.urls')),

    # HTMX views
    path('htmx/object-selector/', htmx.ObjectSelectorView.as_view(), name='htmx_object_selector'),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/core/', include('core.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/vpn/', include('vpn.api.urls')),
    path('api/wireless/', include('wireless.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),

    path(
        "api/schema/",
        cache_page(timeout=86400, key_prefix=f"api_schema_{settings.RELEASE.version}")(
            SpectacularAPIView.as_view()
        ),
        name="schema",
    ),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),

    # GraphQL
    path('graphql/', NetBoxGraphQLView.as_view(schema=schema), name='graphql'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', MediaView.as_view(), name='media'),
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),
]

# django-debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    _patterns.append(path('__debug__/', include(debug_toolbar.urls)))

# Prometheus metrics
if settings.METRICS_ENABLED:
    _patterns.append(path('', include('django_prometheus.urls')))

# Prepend BASE_PATH
urlpatterns = [
    path(settings.BASE_PATH, include(_patterns))
]

handler404 = 'netbox.views.errors.handler_404'
handler500 = 'netbox.views.errors.handler_500'

netbox/netbox-4.4.4/netbox/tenancy/api/urls.py
from netbox.api.routers import NetBoxRouter
from . import views


router = NetBoxRouter()
router.APIRootView = views.TenancyRootView

# Tenants
router.register('tenant-groups', views.TenantGroupViewSet)
router.register('tenants', views.TenantViewSet)

# Contacts
router.register('contact-groups', views.ContactGroupViewSet)
router.register('contact-roles', views.ContactRoleViewSet)
router.register('contacts', views.ContactViewSet)
router.register('contact-assignments', views.ContactAssignmentViewSet)

app_name = 'tenancy-api'
urlpatterns = router.urls

netbox/netbox-4.4.4/netbox/tenancy/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views  # noqa F401

app_name = 'tenancy'
urlpatterns = [

    path('tenant-groups/', include(get_model_urls('tenancy', 'tenantgroup', detail=False))),
    path('tenant-groups/<int:pk>/', include(get_model_urls('tenancy', 'tenantgroup'))),

    path('tenants/', include(get_model_urls('tenancy', 'tenant', detail=False))),
    path('tenants/<int:pk>/', include(get_model_urls('tenancy', 'tenant'))),

    path('contact-groups/', include(get_model_urls('tenancy', 'contactgroup', detail=False))),
    path('contact-groups/<int:pk>/', include(get_model_urls('tenancy', 'contactgroup'))),

    path('contact-roles/', include(get_model_urls('tenancy', 'contactrole', detail=False))),
    path('contact-roles/<int:pk>/', include(get_model_urls('tenancy', 'contactrole'))),

    path('contacts/', include(get_model_urls('tenancy', 'contact', detail=False))),
    path('contacts/<int:pk>/', include(get_model_urls('tenancy', 'contact'))),

    path('contact-assignments/', include(get_model_urls('tenancy', 'contactassignment', detail=False))),
    path('contact-assignments/<int:pk>/', include(get_model_urls('tenancy', 'contactassignment'))),

]

netbox/netbox-4.4.4/netbox/vpn/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views  # noqa F401

app_name = 'vpn'
urlpatterns = [

    path('tunnel-groups/', include(get_model_urls('vpn', 'tunnelgroup', detail=False))),
    path('tunnel-groups/<int:pk>/', include(get_model_urls('vpn', 'tunnelgroup'))),

    path('tunnels/', include(get_model_urls('vpn', 'tunnel', detail=False))),
    path('tunnels/<int:pk>/', include(get_model_urls('vpn', 'tunnel'))),

    path('tunnel-terminations/', include(get_model_urls('vpn', 'tunneltermination', detail=False))),
    path('tunnel-terminations/<int:pk>/', include(get_model_urls('vpn', 'tunneltermination'))),

    path('ike-proposals/', include(get_model_urls('vpn', 'ikeproposal', detail=False))),
    path('ike-proposals/<int:pk>/', include(get_model_urls('vpn', 'ikeproposal'))),

    path('ike-policies/', include(get_model_urls('vpn', 'ikepolicy', detail=False))),
    path('ike-policies/<int:pk>/', include(get_model_urls('vpn', 'ikepolicy'))),

    path('ipsec-proposals/', include(get_model_urls('vpn', 'ipsecproposal', detail=False))),
    path('ipsec-proposals/<int:pk>/', include(get_model_urls('vpn', 'ipsecproposal'))),

    path('ipsec-policies/', include(get_model_urls('vpn', 'ipsecpolicy', detail=False))),
    path('ipsec-policies/<int:pk>/', include(get_model_urls('vpn', 'ipsecpolicy'))),

    path('ipsec-profiles/', include(get_model_urls('vpn', 'ipsecprofile', detail=False))),
    path('ipsec-profiles/<int:pk>/', include(get_model_urls('vpn', 'ipsecprofile'))),

    path('l2vpns/', include(get_model_urls('vpn', 'l2vpn', detail=False))),
    path('l2vpns/<int:pk>/', include(get_model_urls('vpn', 'l2vpn'))),

    path('l2vpn-terminations/', include(get_model_urls('vpn', 'l2vpntermination', detail=False))),
    path('l2vpn-terminations/<int:pk>/', include(get_model_urls('vpn', 'l2vpntermination'))),

]

netbox/netbox-4.4.4/netbox/tenancy/models/contacts.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from netbox.models import ChangeLoggedModel, NestedGroupModel, OrganizationalModel, PrimaryModel
from netbox.models.features import CustomFieldsMixin, ExportTemplatesMixin, TagsMixin, has_feature
from tenancy.choices import *

__all__ = (
    'ContactAssignment',
    'Contact',
    'ContactGroup',
    'ContactRole',
)


class ContactGroup(NestedGroupModel):
    """
    An arbitrary collection of Contacts.
    """
    class Meta:
        ordering = ['name']
        constraints = (
            models.UniqueConstraint(
                fields=('parent', 'name'),
                name='%(app_label)s_%(class)s_unique_parent_name'
            ),
        )
        verbose_name = _('contact group')
        verbose_name_plural = _('contact groups')


class ContactRole(OrganizationalModel):
    """
    Functional role for a Contact assigned to an object.
    """
    class Meta:
        ordering = ('name',)
        verbose_name = _('contact role')
        verbose_name_plural = _('contact roles')


class Contact(PrimaryModel):
    """
    Contact information for a particular object(s) in NetBox.
    """
    groups = models.ManyToManyField(
        to='tenancy.ContactGroup',
        related_name='contacts',
        related_query_name='contact',
        blank=True
    )
    name = models.CharField(
        verbose_name=_('name'),
        max_length=100,
        db_collation="natural_sort"
    )
    title = models.CharField(
        verbose_name=_('title'),
        max_length=100,
        blank=True
    )
    phone = models.CharField(
        verbose_name=_('phone'),
        max_length=50,
        blank=True
    )
    email = models.EmailField(
        verbose_name=_('email'),
        blank=True
    )
    address = models.CharField(
        verbose_name=_('address'),
        max_length=200,
        blank=True
    )
    link = models.URLField(
        verbose_name=_('link'),
        blank=True
    )

    clone_fields = (
        'groups', 'name', 'title', 'phone', 'email', 'address', 'link',
    )

    class Meta:
        ordering = ['name']
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

    def __str__(self):
        return self.name


class ContactAssignment(CustomFieldsMixin, ExportTemplatesMixin, TagsMixin, ChangeLoggedModel):
    object_type = models.ForeignKey(
        to='contenttypes.ContentType',
        on_delete=models.CASCADE
    )
    object_id = models.PositiveBigIntegerField()
    object = GenericForeignKey(
        ct_field='object_type',
        fk_field='object_id'
    )
    contact = models.ForeignKey(
        to='tenancy.Contact',
        on_delete=models.PROTECT,
        related_name='assignments'
    )
    role = models.ForeignKey(
        to='tenancy.ContactRole',
        on_delete=models.PROTECT,
        related_name='assignments'
    )
    priority = models.CharField(
        verbose_name=_('priority'),
        max_length=50,
        choices=ContactPriorityChoices,
        blank=True,
        null=True
    )

    clone_fields = ('object_type', 'object_id', 'role', 'priority')

    class Meta:
        ordering = ('contact', 'priority', 'role', 'pk')
        indexes = (
            models.Index(fields=('object_type', 'object_id')),
        )
        constraints = (
            models.UniqueConstraint(
                fields=('object_type', 'object_id', 'contact', 'role'),
                name='%(app_label)s_%(class)s_unique_object_contact_role'
            ),
        )
        verbose_name = _('contact assignment')
        verbose_name_plural = _('contact assignments')

    def __str__(self):
        if self.priority:
            return f"{self.contact} ({self.get_priority_display()}) -> {self.object}"
        return str(f"{self.contact} -> {self.object}")

    def get_absolute_url(self):
        return reverse('tenancy:contact', args=[self.contact.pk])

    def clean(self):
        super().clean()

        # Validate the assigned object type
        if not has_feature(self.object_type, 'contacts'):
            raise ValidationError(
                _("Contacts cannot be assigned to this object type ({type}).").format(type=self.object_type)
            )

    def to_objectchange(self, action):
        objectchange = super().to_objectchange(action)
        objectchange.related_object = self.object
        return objectchange

netbox/netbox-4.4.4/netbox/tenancy/models/tenants.py
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from netbox.models import NestedGroupModel, PrimaryModel
from netbox.models.features import ContactsMixin

__all__ = (
    'Tenant',
    'TenantGroup',
)


class TenantGroup(NestedGroupModel):
    """
    An arbitrary collection of Tenants.
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=100,
        unique=True,
        db_collation="natural_sort"
    )
    slug = models.SlugField(
        verbose_name=_('slug'),
        max_length=100,
        unique=True
    )

    class Meta:
        ordering = ['name']
        verbose_name = _('tenant group')
        verbose_name_plural = _('tenant groups')


class Tenant(ContactsMixin, PrimaryModel):
    """
    A Tenant represents an organization served by the NetBox owner. This is typically a customer or an internal
    department.
    """
    name = models.CharField(
        verbose_name=_('name'),
        max_length=100,
        db_collation="natural_sort"
    )
    slug = models.SlugField(
        verbose_name=_('slug'),
        max_length=100
    )
    group = models.ForeignKey(
        to='tenancy.TenantGroup',
        on_delete=models.SET_NULL,
        related_name='tenants',
        blank=True,
        null=True
    )

    clone_fields = (
        'group', 'description',
    )

    class Meta:
        ordering = ['name']
        constraints = (
            models.UniqueConstraint(
                fields=('group', 'name'),
                name='%(app_label)s_%(class)s_unique_group_name',
                violation_error_message=_("Tenant name must be unique per group.")
            ),
            models.UniqueConstraint(
                fields=('name',),
                name='%(app_label)s_%(class)s_unique_name',
                condition=Q(group__isnull=True)
            ),
            models.UniqueConstraint(
                fields=('group', 'slug'),
                name='%(app_label)s_%(class)s_unique_group_slug',
                violation_error_message=_("Tenant slug must be unique per group.")
            ),
            models.UniqueConstraint(
                fields=('slug',),
                name='%(app_label)s_%(class)s_unique_slug',
                condition=Q(group__isnull=True)
            ),
        )
        verbose_name = _('tenant')
        verbose_name_plural = _('tenants')

    def __str__(self):
        return self.name

netbox/netbox-4.4.4/netbox/templates/tenancy/contact.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block breadcrumbs %}
  {{ block.super }}
  {% if object.group %}
    <li class="breadcrumb-item"><a href="{% url 'tenancy:contact_list' %}?group_id={{ object.group.pk }}">{{ object.group }}</a></li>
  {% endif %}
{% endblock breadcrumbs %}

{% block content %}
  <div class="row">
    <div class="col col-12 col-md-7">
      <div class="card">
        <h2 class="card-header">{% trans "Contact" %}</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">{% trans "Groups" %}</th>
            <td>
              {% if object.groups.all|length > 0 %}
                <ol class="list-unstyled mb-0">
                  {% for group in object.groups.all %}
                    <li>{{ group|linkify|placeholder }}</li>
                  {% endfor %}
                </ol>
              {% else %}
                {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">{% trans "Name" %}</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Title" %}</th>
            <td>{{ object.title|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Phone" %}</th>
            <td>
              {% if object.phone %}
                <a href="tel:{{ object.phone }}">{{ object.phone }}</a>
              {% else %}
                {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">{% trans "Email" %}</th>
            <td>
              {% if object.email %}
                <a href="mailto:{{ object.email }}">{{ object.email }}</a>
              {% else %}
                {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">{% trans "Address" %}</th>
            <td>{{ object.address|linebreaksbr|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Link" %}</th>
            <td>
              {% if object.link %}
                <a href="{{ object.link }}">{{ object.link }}</a>
              {% else %}
                {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">{% trans "Description" %}</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
        </table>
      </div>
      {% include 'inc/panels/tags.html' %}
      {% plugin_left_page object %}
    </div>
    <div class="col col-md-5">
      {% include 'inc/panels/comments.html' %}
      {% include 'inc/panels/custom_fields.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col col-md-12">
      <div class="card">
        <h2 class="card-header">{% trans "Assignments" %}</h2>
        {% htmx_table 'tenancy:contactassignment_list' contact_id=object.pk %}
      </div>
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/tenancy/contactgroup.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block breadcrumbs %}
  {{ block.super }}
  {% for contactgroup in object.get_ancestors %}
    <li class="breadcrumb-item"><a href="{% url 'tenancy:contactgroup_list' %}?parent_id={{ contactgroup.pk }}">{{ contactgroup }}</a></li>
  {% endfor %}
{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-12 col-md-6">
      <div class="card">
        <h2 class="card-header">{% trans "Contact Group" %}</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">{% trans "Name" %}</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Description" %}</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Parent" %}</th>
            <td>{{ object.parent|linkify|placeholder }}</td>
          </tr>
        </table>
      </div>
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
      {% plugin_left_page object %}
    </div>
    <div class="col col-12 col-md-6">
      {% include 'inc/panels/related_objects.html' %}
      {% include 'inc/panels/custom_fields.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        {% trans "Child Groups" %}
        {% if perms.tenancy.add_contactgroup %}
          <div class="card-actions">
            <a href="{% url 'tenancy:contactgroup_add' %}?parent={{ object.pk }}" class="btn btn-ghost-primary btn-sm">
              <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Add Contact Group" %}
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'tenancy:contactgroup_list' parent_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/tenancy/contactrole.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item"><a href="{% url 'tenancy:contactrole_list' %}">{% trans "Contact Roles" %}</a></li>
{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-12 col-md-6">
      <div class="card">
        <h2 class="card-header">{% trans "Contact Role" %}</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">{% trans "Name" %}</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Description" %}</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
        </table>
      </div>
      {% include 'inc/panels/tags.html' %}
      {% plugin_left_page object %}
    </div>
    <div class="col col-12 col-md-6">
      {% include 'inc/panels/related_objects.html' %}
      {% include 'inc/panels/custom_fields.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/tenancy/object_contacts.html
{% extends 'generic/object_children.html' %}
{% load helpers %}
{% load i18n %}

{% block extra_controls %}
  {% if perms.tenancy.add_contactassignment %}
    <a href="{% url 'tenancy:contactassignment_add' %}?object_type={{ object|content_type_id }}&object_id={{ object.pk }}&return_url={% action_url object 'contacts' pk=object.pk %}" class="btn btn-primary">
      <i class="mdi mdi-plus-thick" aria-hidden="true"></i> {% trans "Add a contact" %}
    </a>
  {% endif %}
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/tenancy/tenant.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load i18n %}

{% block breadcrumbs %}
  {{ block.super }}
  {% if object.group %}
    <li class="breadcrumb-item"><a href="{% url 'tenancy:tenant_list' %}?group_id={{ object.group.pk }}">{{ object.group }}</a></li>
  {% endif %}
{% endblock breadcrumbs %}

{% block content %}
  <div class="row">
    <div class="col col-12 col-md-7">
      <div class="card">
        <h2 class="card-header">{% trans "Tenant" %}</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">{% trans "Group" %}</th>
            <td>{{ object.group|linkify|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Description" %}</th>
            <td>{{ object.description|placeholder }}</td>
          </tr>
        </table>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
      {% plugin_left_page object %}
    </div>
    <div class="col col-md-5">
      {% include 'inc/panels/related_objects.html' %}
      {% plugin_right_page object %}
    </div>
  </div>
  <div class="row">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}

netbox/netbox-4.4.4/netbox/templates/tenancy/tenantgroup.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load plugins %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block breadcrumbs %}
  {{ block.super }}
  {% for tenantgroup in object.get_ancestors %}
    <li class="breadcrumb-item"><a href="{% url 'tenancy:tenantgroup_list' %}?parent_id={{ tenantgroup.pk }}">{{ tenantgroup }}</a></li>
  {% endfor %}
{% endblock %}

{% block extra_controls %}
  {% if perms.tenancy.add_tenant %}
    <a href="{% url 'tenancy:tenant_add' %}?group={{ object.pk }}" class="btn btn-primary">
      <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Add Tenant" %}
    </a>
  {% endif %}
{% endblock extra_controls %}

{% block content %}
<div class="row mb-3">
	<div class="col col-12 col-md-6">
    <div class="card">
      <h2 class="card-header">{% trans "Tenant Group" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">{% trans "Name" %}</th>
          <td>{{ object.name }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Description" %}</th>
          <td>{{ object.description|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">{% trans "Parent" %}</th>
          <td>{{ object.parent|linkify|placeholder }}</td>
        </tr>
      </table>
    </div>
    {% include 'inc/panels/tags.html' %}
    {% include 'inc/panels/comments.html' %}
    {% plugin_left_page object %}
  </div>
	<div class="col col-12 col-md-6">
    {% include 'inc/panels/related_objects.html' %}
    {% include 'inc/panels/custom_fields.html' %}
    {% plugin_right_page object %}
	</div>
</div>
<div class="row mb-3">
	<div class="col col-md-12">
    <div class="card">
      <h2 class="card-header">
        {% trans "Child Groups" %}
        {% if perms.tenancy.add_tenantgroup %}
          <div class="card-actions">
            <a href="{% url 'tenancy:tenantgroup_add' %}?parent={{ object.pk }}" class="btn btn-ghost-primary btn-sm">
              <span class="mdi mdi-plus-thick" aria-hidden="true"></span> {% trans "Add Tenant Group" %}
            </a>
          </div>
        {% endif %}
      </h2>
      {% htmx_table 'tenancy:tenantgroup_list' parent_id=object.pk %}
    </div>
    {% plugin_full_width_page object %}
  </div>
</div>
{% endblock %}